// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.5.10'

    repositories {
        maven { url 'https://jitpack.io' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20'
    }
}

allprojects {
    // 减少缓存大小
    configurations.configureEach {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
        resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
    }

    // 清理构建目录
    tasks.withType(Delete).tap {
        configureEach {
            delete fileTree(dir: buildDir, include: '**/*.bin')
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}